variable "firenet_transit_gateway_name" {}
variable "firenet_transit_peer_gateway_name" {}
variable "firenet_spoke_gateway_name" {}
variable "firewall_vpc_id" {}
variable "firewall_instance_id" {}
variable "firewall_public_ip" {}
variable "firewall_name" {}
variable "firewall_username" {}
variable "firewall_password" {}
